minha_string = " Olá, meu nome é Rhuan Carlos. Sou dev FullStak Web "
print(minha_string + "\n")

print("capitalize")
print(minha_string.capitalize() + "\n")
print("lower")
print(minha_string.lower() + "\n")
print("upper")
print(minha_string.upper() + "\n")
print("strip")
print(minha_string.strip() + "\n")
print("replace")
print(minha_string.replace("a","A",-1))
print(minha_string.replace("Carlos","Oliver"))
print(minha_string.replace("Stak","Stack") + "\n")
print("len")
print(f"{len(minha_string)} \n")
print("index")
print(f"{minha_string.index('Rhuan')}")
print(f"{minha_string.index('h')}")
print(f"{minha_string.index('e')} \n")
print("acessing str[]")
print(minha_string[17:23])
print(minha_string[-17:-5] + "\n")
print("in")
print("desktop" in minha_string)
print("web" in minha_string)
print("web" in minha_string.lower())
print("Web" in minha_string)
print("\n")
print('Multi Line """text_here""" ')
print("""Olá, meu nome é Rhuan Carlos. 
      Sou dev FullStak Web""")
print("\n")
print("Multi Line \ n ")
print("Olá, meu nome é Rhuan Carlos.\n Sou dev FullStak Web")